import type { Metadata } from "next";
import "./globals.scss";
import { Montserrat } from "next/font/google";
import Provider from "./utils/Provider";


const montserrat = Montserrat({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
